name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          user: tjuedema
          plugins_errors_fatal: yes
      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          filename: leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          user: TannerBJ
          plugins_errors_fatal: yes
      - name: stackoverflow
        uses: lowlighter/metrics@latest
        with:
          filename: stackoverflow.svg
          token: NOT_NEEDED
          base: ""
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 20178809
          plugin_stackoverflow_sections: 
          plugin_stackoverflow_limit: 1
